title: Adam Lashley
logo: "/images/logo.png?raw=true"
description: >
  I'm a Master's of Data Science student graduating in 2022.
  <br><br>
  Through my demonstrated history of developing end-to-end data solutions, I have developed a variety of transferrable 
  skillsets in the areas of computer vision, deep learning, and natural language processing. I enjoy collaborating 
  in teams and developing novel solutions to challenging problems.
  <br><br>
  <a href="https://www.linkedin.com/in/adamlashley/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal